I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 42, in script
    m "It's like an interactive book that you can read on a computer or a console."
Exception: Sayer 'm' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 42, in script
    m "It's like an interactive book that you can read on a computer or a console."
  File "/home/incspn/Downloads/renpy-7.3.5-sdk/renpy/ast.py", line 678, in execute
    who = eval_who(self.who, self.who_fast)
  File "/home/incspn/Downloads/renpy-7.3.5-sdk/renpy/ast.py", line 576, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'm' is not defined.

Linux-5.8.0-26-generic-x86_64-with-debian-bullseye-sid
Ren'Py 7.3.5.606
El Cuenta Cuentos Ocelotl2 1.0
Sat Nov  7 16:44:43 2020
