I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 6, in script
    image bg altar = im.FactorScale("bg altarfull.jpg")
  File "game/script.rpy", line 6, in <module>
    image bg altar = im.FactorScale("bg altarfull.jpg")
NameError: name 'image' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 6, in script
    image bg altar = im.FactorScale("bg altarfull.jpg")
  File "/home/incspn/Downloads/renpy-7.3.5-sdk/renpy/ast.py", line 1013, in execute
    img = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "/home/incspn/Downloads/renpy-7.3.5-sdk/renpy/python.py", line 2052, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 6, in <module>
    image bg altar = im.FactorScale("bg altarfull.jpg")
NameError: name 'image' is not defined

Linux-5.8.0-26-generic-x86_64-with-debian-bullseye-sid
Ren'Py 7.3.5.606
El Cuenta Cuentos Ocelotl2 1.0
Sat Nov  7 00:11:03 2020
